name: 'deploy'

on:
  push:
    branches:
      - PSCAN-4-search-product

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@dokku.tuxwin.fr:3022/pantryscan-api'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_DOKKU }}
